# Generated by Django 5.1 on 2024-08-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(blank=True, max_length=15, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('residence', models.CharField(blank=True, max_length=200, null=True)),
                ('reference', models.CharField(blank=True, max_length=200, null=True)),
                ('why_buy_house', models.CharField(blank=True, max_length=100, null=True)),
                ('adults', models.IntegerField(blank=True, null=True)),
                ('children', models.IntegerField(blank=True, null=True)),
                ('senior_citizens', models.IntegerField(blank=True, null=True)),
                ('have_pets', models.CharField(blank=True, max_length=10, null=True)),
                ('current_residence_area', models.CharField(blank=True, max_length=100, null=True)),
                ('religious_preference', models.CharField(blank=True, max_length=50, null=True)),
                ('workplace_area', models.CharField(blank=True, max_length=100, null=True)),
                ('school_area', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_locations', models.CharField(blank=True, max_length=200, null=True)),
                ('decision_driven_by', models.CharField(blank=True, max_length=20, null=True)),
                ('dependent_on_sale', models.CharField(blank=True, max_length=10, null=True)),
                ('looking_since', models.CharField(blank=True, max_length=50, null=True)),
                ('time_to_seal_deal', models.CharField(blank=True, max_length=50, null=True)),
                ('bedrooms', models.CharField(blank=True, max_length=50, null=True)),
                ('attached_washrooms', models.CharField(blank=True, max_length=50, null=True)),
                ('servant_room', models.CharField(blank=True, max_length=10, null=True)),
                ('puja_room', models.CharField(blank=True, max_length=10, null=True)),
                ('min_carpet_area', models.CharField(blank=True, max_length=100, null=True)),
                ('vastu_preferences', models.CharField(blank=True, max_length=200, null=True)),
                ('flats_per_floor', models.CharField(blank=True, max_length=50, null=True)),
                ('floor_preference', models.CharField(blank=True, max_length=50, null=True)),
                ('private_elevator', models.CharField(blank=True, max_length=10, null=True)),
                ('central_air_conditioning', models.CharField(blank=True, max_length=10, null=True)),
                ('min_parking_slots', models.CharField(blank=True, max_length=10, null=True)),
                ('stack_parking', models.CharField(blank=True, max_length=50, null=True)),
                ('property_age', models.CharField(blank=True, max_length=50, null=True)),
                ('society_type', models.CharField(blank=True, max_length=100, null=True)),
                ('amenities', models.CharField(blank=True, max_length=200, null=True)),
                ('budget_min', models.CharField(blank=True, max_length=20, null=True)),
                ('budget_max', models.CharField(blank=True, max_length=20, null=True)),
                ('down_payment_percentage', models.CharField(blank=True, max_length=10, null=True)),
                ('loan_approved_amount', models.CharField(blank=True, max_length=20, null=True)),
                ('specific_needs', models.TextField(blank=True, null=True)),
                ('concerns', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
